# Preface {.unnumbered}

## Description

Topics included are optimization, numerical integration, bootstrapping, cross-validation and Jackknife, density estimation, smoothing, and use of the statistical computer package of S-plus/R.

### Prerequisites

MATH 4752/6752 -- Mathematical Statistics II, and the ability to program in a high-level language.

### Instructor

[Chi-Kuang Yeh](https://chikuang.github.io/), I am an Assistant Professor in the Department of Mathematics and Statistics, Georgia State University.

-   Office: Suite 1407, 25 Park Place.
-   Email: [cyeh\@gsu.edu](mailto:cyeh@gsu.edu).

## Office Hour

14:00--15:00 on Tuesday and Wednesday.

## Grade Distribution

-   Assignments: 40%
-   Exam 1: 15%
-   Exam 2: 15%
-   Project: 30%

## Assignment

-   [x] Assignment 1: Due on September 12, 2025
-   [x] Assignment 2: Due on September 22, 2025
-   [ ] Assignment 3: Due on October 22, 2025
-   [ ] Assignment 4: TBA

## Midterm

-   [x] Midterm 1 on October 8, 2025
-   [ ] Midterm 2 on November 12, 2025

## Project

-   [ ] Report: Due Date TBA
-   [ ] Presentation: Date TBA

## Topics and Corresponding Lectures

Those chapters are based on the lecture notes. This part will be updated frequently.

| Topic                                        | Lecture Covered |
|----------------------------------------------|:---------------:|
| R Programming                                |      1--2       |
| Numerical Approaches and Optimization in 1-D |      3--5       |
| Review for Distribution                      |      6--7       |
| Random Variable Generation                   |      8--10      |
| Monte Carlo and Integration                  |     11--15      |
| Exam 1                                       |       13        |
| Bootstrap and Jackknife                      |      16--       |
| Cross-validation                             |       TBA       |
| Exam 2                                       |       23        |
| Smoothing                                    |       TBA       |
| Density estimation                           |       TBA       |

## Recommended Textbooks

-   Givens, G.H. and Hoeting, J.A. (2012). [*Computational Statistics*](https://www.stat.colostate.edu/computationalstatistics/). Wiley, New York.

-   Rizzo, M.L. (2007) [*Statistical Computing with R*](https://a-roshani.ir/files/SC/%5B4%5D%20%5BMaria%20L.%20Rizzo%5D%5B2019%5D%20Statistical%20Computing%20%20with%20R,%20Second%20Edition.pdf). CRC Press, Roca Baton.

-   Hothorn, T. and Everitt, B.S. (2006). [*A Handbook of Statistical Analyses Using R*](https://digitallibrary.tsu.ge/book/2019/september/books/A-Handbook-of-Statistical-Analyses.pdf). CRC Press, Boca Raton.

## Side Readings

-   Wickham, H., Çetinkaya-Rundel, M. and Grolemund, G. (2023). [*R for Data Science*](https://r4ds.hadley.nz/). O'Reilly.
