{
  "hash": "72d52f716bf78707d2561b837184102d",
  "result": {
    "engine": "knitr",
    "markdown": "# Resampling, Jackknife and Bootstrap\n\n\\newcommand{\\E}{\\mathbb E}\n\\newcommand{\\R}{\\mathbb{R}}\n\\newcommand{\\var}{\\mathbb{V}ar}\n\\newcommand{\\bx}{\\mathbf{x}}\n\\newcommand{\\bX}{\\mathbf{X}}\n\\newcommand{\\cov}{\\mathbb{C}ov}\n\\newcommand{\\mse}{\\mathrm{MSE}}\n\\newcommand{\\corr}{\\mathbb{C}orr}\n\\newcommand{\\unif}{\\operatorname{Unif}}\n\\newcommand{\\geom}{\\operatorname{Geom}}\n\\newcommand{\\bet}{\\operatorname{Beta}}\n\\newcommand{\\bern}{\\operatorname{Bern}}\n\\newcommand{\\iid}{\\overset{iid}{\\sim}}\n\\newcommand{\\ef}{\\operatorname{Eff}}\n\\newcommand{\\htt}{\\hat \\theta}\n\\newcommand{\\b}{\\mathbb b}\n\n\n\n## Introduction\n\nThis chapter continues from the previous chapter, introducing more resampling methods; jackknife and bootstrap techniques.\n\n## Disclaimer\n\nMost of the contents of this chapter are mainly from the reference book, Chapter 8 of Rizzo, M.L. (2007). *Statistical Computing with R*. CRC Press, Roca Baton.\n\n## Resampling methods\n\n*Resampling methods* is a way to use the observed data to generate hypothetical samples. It treats an observed sample as a *finite population*, and random samples are generated/resampled from it to estimate population characteristics and make inferences about the sampled population. It is useful when:\n\n-   Do not know the underlying distribution of a population\n\n-   The formula may be difficult to be calculated.\n\nSome commonly used resampling methods include:\n\n-   **Cross-validation**: Cross-validation is a model validation technique for assessing how the results of a statistical analysis will generalize to an independent data set. It is mainly used in settings where the goal is prediction, and one wants to estimate how accurately a predictive model will perform in practice.\n\n-   **Bootstrap**: Bootstrap methods are often used when the distribution of the target population is not specified; the sample is the only information available.\n\n-   **Jackknife**: The jackknife is a resampling technique used to estimate the bias and variance of a statistic. It is like a leave-one-out (LOO) cross-validation.\n\n-   **Permutation tests**: Permutation tests are a type of non-parametric statistical test that involves rearranging the data points to test a hypothesis. They are used to determine whether the observed effect is statistically significant by comparing it to the distribution of effects obtained through random permutations of the data.\n\n## Estimators\n\n### Bias-Variance Tradeoff of an estimator\n\nIn statistics, the bias-variance tradeoff is the property of a model that the variance of the parameter estimated across samples can be reduced by increasing the bias in the estimated parameters. If we look at the Mean square error (MSE) of an estimator $\\hat \\theta$ for a parameter $\\theta$:\n\n::: {.callout-definition title=\"Mean Square Errors\"}\nSuppose we have a parameter $\\theta$ and an estimator $\\hat \\theta$. The mean square error (MSE) of the estimator is defined as $$\\mathrm{MSE}_{\\theta}(\\hat \\theta)=\\mathbb E[(\\hat \\theta-\\theta )^2 ]= \\mathbb{V}ar(\\hat \\theta) + [\\mathbb b(\\hat \\theta)]^2,$$ where $\\mathbb b$ is the bias of the estimator.\n:::\n\n::: {.callout-note title=\"Derivation\"}\nWe start with the definition of the mean squared error (MSE):\n\n$$\n\\mathrm{MSE}_\\theta(\\hat \\theta)\n= \\mathbb E\\big[(\\hat \\theta- \\theta)^2\\big].\n$$\n\nAdd and subtract $\\mathbb E[\\hat \\theta]$ inside the square: $$\n\\mathbb E\\big[(\\hat \\theta- \\theta)^2\\big]\n= \\mathbb E\\big[(\\hat \\theta- \\mathbb E[\\hat \\theta] + \\mathbb E[\\hat \\theta] - \\theta)^2\\big].\n$$\n\nExpand the square: $$\n\\mathbb E\\big[(\\hat \\theta- \\mathbb E[\\hat \\theta])^2\\big]\n+ 2\\,\\mathbb E\\big[(\\hat \\theta- \\mathbb E[\\hat \\theta])(\\mathbb E[\\hat \\theta] - \\theta)\\big]\n+ (\\mathbb E[\\hat \\theta] - \\theta)^2.\n$$\n\nThe middle term vanishes because $$\n\\mathbb E\\big[\\hat \\theta- \\mathbb E[\\hat \\theta]\\big] = 0.\n$$\n\nHence, $$\n\\mathbb E\\big[(\\hat \\theta- \\theta)^2\\big]\n= \\mathbb E\\big[(\\hat \\theta- \\mathbb E[\\hat \\theta])^2\\big]\n+ (\\mathbb E[\\hat \\theta] - \\theta)^2.\n$$\n\nRecognizing that $$\n\\mathbb{V}ar(\\hat \\theta) = \\mathbb E\\big[(\\hat \\theta- \\mathbb E[\\hat \\theta])^2\\big]\n\\quad \\text{and} \\quad\nb(\\hat \\theta) = \\mathbb E[\\hat \\theta] - \\theta,\n$$ we obtain the bias–variance decomposition: $$\n\\boxed{\n\\mathbb E\\big[(\\hat \\theta- \\theta)^2\\big]\n= \\mathbb{V}ar(\\hat \\theta) + \\mathbb b^2(\\hat \\theta)^2.}\n$$\n:::\n\n**Questions**: Why do we care about the bias? Can we always find an unbiased estimator? What does it mean?\n\nFor most of the course, we focus on the *unbiased estimator*. This may often be obtained from using the LLN. Then, such as in the MC Chapter, we can compare the (relative) efficiency between the estimators, and discuss about the variance reduction.\n\n## Bootstrap\n\nBootstrap estimates of a sampling distribution are analogous to the idea of *density estimation* (will be introduced in a later chapter). We construct a histogram of a sample to obtain an estimate of the shape of the density function. The histogram is not the density, but in a nonparametric problem, can be viewed as a reasonable estimate of the density. We have methods to generate random samples from completely specified densities; bootstrap generates random samples from the empirical distribution of the sample.\n\nSuppose we have an observed random sample $x=(x_1,\\dots,x_n)$ from a distribution $F$. If $X^\\ast$ is selected at random from $x$, then $$P(X^\\ast=x_i)=1/n,\\quad i=1,\\dots,n.$$\n\nResampling generates a random sample $X^\\ast_1,\\dots,X_n^\\ast$ by *sampling with replacement* from the observed sample $x$. Then the RVs $X_i^\\ast$ are i.i.d. and uniformly distributed on the observed data points $\\{x_1,\\dots,x_n\\}$.\n\nThe empirical distribution function (ecdf) $F_n(x)$ is an estimator of $F(x)$. It can be shown that $F_n(x)$ is a sufficient statistic for $F(x)$; that is, all the information about $F(x)$ that is contained in the sample is also contained in $F_n(x)$. Moreover, $F_n(x)$ is itself the distribution function of a random variable; namely the random variable that is uniformly distributed on the set $\\{x_1, \\dots , x_n\\}$. Hence the empirical cdf $F_n$ is the cdf of $X^\\ast$. Thus in bootstrap, there are two approximations. The ecdf $F_n$ is an approximation to the cdf $F_X$. The ecdf $F_m^\\ast$ of the bootstrap replicates is an approximation to the ecdf $F_n$. Resampling from the sample $x$ is equivalent to generating random samples from the distribution $F_n(x)$. The two approximations can be represented by the diagram\n\n$$\n\\begin{aligned}\nF & \\rightarrow X \\rightarrow F_n \\\\\nF_n & \\rightarrow X^* \\rightarrow F_n^* .\n\\end{aligned}\n$$\n\nTo generate a bootstrap random sample by resampling $x$, generate $n$ random integers $\\{i_1,\\dots, i_n\\}$ uniformly distributed on $\\{1,\\dots , n\\}$ and select the bootstrap sample $x^\\ast = (x_{i_1} ,\\dots , x_{i_n} )$.\n\n------------------------------------------------------------------------\n\nLet $\\theta$ be the parameter of interest (could be a vector), and $\\hat \\theta$ be its estimator. Then the bootstrap estimate of the distribution of $\\hat \\theta$ is obtained as follows.\n\n::: {.callout-algorithm title = \"Procedure of Bootstrap\"}\n\n1.  For each bootstrap replicate, indexed $b = 1, \\dots, B$:\n    (a) Generate sample $x^{\\ast (b)} = x_1^\\ast,\\dots,x_n^\\ast$ by sampling with replacement from the observed sample $x_1,\\dots,x_n$.\n    (b) Compute the $b$th replicate $\\hat \\theta^{(b)}$ from the $b$th bootstrap sample.\n2.  The bootstrap estimate of $F_{\\hat \\theta}(\\cdot)$ is the empirical distribution of the replicates $\\hat \\theta^{(1)},\\dots ,\\hat \\theta^{(B)}$.\n\n:::\n\n::: {.callout-example title=\"Empirical CDF and Bootstrap Distribution\"}\nSuppose that we have observed the sample\n\n$$x = \\{2, 2, 1, 1, 5, 4, 4, 3, 1, 2\\}.$$\n\nResampling from $x$ we select $1, 2, 3, 4$, or $5$ with probabilities $0.3, 0.3, 0.1, 0.2$, and $0.1$, respectively, so the cdf $F_{X^\\ast}$ of a randomly selected replicate is exactly the ecdf $F_n(x)$:\n\n$$\nF_{X *}(x)=F_n(x)= \\begin{cases}0, & x<1 ; \\\\ 0.3, & 1 \\leq x<2 ; \\\\ 0.6, & 2 \\leq x<3 ; \\\\ 0.7, & 3 \\leq x<4 ; \\\\ 0.9, & 4 \\leq x<5 ; \\\\ 1, & x \\geq 5 .\\end{cases}\n$$\n\nNote that if $F_n$ is not close to $F_X$ then the distribution of the replicates will not be close to $F_X$. The sample $x$ above is actually a sample from a Poisson(2) distribution. Resampling from $x$ a large number of replicates produces a good estimate of $F_n$ but not a good estimate of $F_X$ , because regardless of how many replicates are drawn, the bootstrap samples will never include $0$.\n:::\n\n### Bootstrap Estimation of Standard Error\n\nRecall that, in normal approximate, the $100(1-\\alpha)$% confidence interval (for $\\mu$) is given as $$\n  \\bar{x}_n \\pm z_{1-\\alpha/2} \\frac{\\sigma}{\\sqrt{n}}.\n$$ In the above formula, we refer\n\n-   $\\sigma/\\sqrt{n}$: as the **standard error** (se).\n-   $z_{1-\\alpha/2}\\cdot \\sigma/\\sqrt{n}$: as the **margin of error**.\n\n::: {.callout-definition title=\"Standard Error\"}\nThe standard error (SE) of a statistic is the standard deviation of its sampling distribution. The se is often used in calculations of confidence intervals.\n:::\n\nTo estimate the $se$ of an estimator $\\htt$, we can use the bootstrap method. Let $\\hat \\theta^{(1)},\\dots,\\hat \\theta^{(B)}$ be the bootstrap replicates. The bootstrap estimate of the standard error of $\\htt$ is given by the sample standard deviation of the replicates:\n\n$$\n\\widehat{s e}\\left(\\hat{\\theta}^*\\right)=\\sqrt{\\frac{1}{B-1} \\sum_{b=1}^B\\left(\\hat{\\theta}^{(b)}-\\overline{\\hat{\\theta}^*}\\right)^2},\n$$ where $\\overline{\\hat{\\theta}^*}=\\frac{1}{B} \\sum_{b=1}^B \\hat{\\theta}^{(b)}$.\n\n::: {.callout-note title = \"Remark for estimating se\"}\n\nThe number of replicates needed for good estimates of standard error is not large; $B = 50$ is usually large enough, and rarely is $B > 200$ necessary.\n\n:::\n\n::: {.callout-example title=\"Bootstrap Estimate of Standard Error\"}\nThe law school data set law in the *bootstrap* package. The data frame contains LSAT (average score on law school admission test score) and GPA (average undergraduate grade point average) for 15 law schools.\n\n| Observation | LSAT | GPA |\n|-------------|------|-----|\n| 1           | 576  | 339 |\n| 2           | 635  | 330 |\n| 3           | 558  | 281 |\n| 4           | 578  | 303 |\n| 5           | 666  | 344 |\n| 6           | 580  | 307 |\n| 7           | 555  | 300 |\n| 8           | 661  | 343 |\n| 9           | 651  | 336 |\n| 10          | 605  | 313 |\n| 11          | 653  | 312 |\n| 12          | 575  | 274 |\n| 13          | 545  | 276 |\n| 14          | 572  | 288 |\n| 15          | 594  | 296 |\n\nThis data set is a random sample from the universe of 82 law schools in law82 (bootstrap). Estimate the correlation between LSAT and GPA scores, and compute the bootstrap estimate of the standard error of the sample correlation.\n\nThe bootstrap procedure is\n\n1.  For each bootstrap replicate, indexed $b = 1,\\dots , B$\n    (a) Generate sample $(\\text{LSAT}^{\\ast (b)}_i, \\text{GPA}^{\\ast (b)}_i), i = 1,\\dots , n$ by sampling with replacement from the observed sample.\n    (b) Compute the $b$th replicate of the correlation $\\hat \\theta^{(b)} = \\mathbb{C}orr(\\text{LSAT}^{\\ast (b)}, \\text{GPA}^{\\ast (b)})$ from the $b$th bootstrap sample.\n2.  The bootstrap estimate of the standard error of $\\hat \\theta$ is the sample standard deviation of the replicates $\\hat \\theta^{(1)},\\dots ,\\hat \\theta^{(B)}$, $\\{R^{(i)}\\}_{i=1}^B$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(bootstrap) #for the law data\nprint(cor(law$LSAT, law$GPA)) # 15 sampled schools in hand\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7763745\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(cor(law82$LSAT, law82$GPA)) # all total 82 schools\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7599979\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#set up the bootstrap\nB <- 200 #number of replicates\nn <- nrow(law) #sample size\nR <- numeric(B) #storage for replicates\n#bootstrap estimate of standard error of R\nfor (b in 1:B) {\n  # randomly select the indices\n  i <- sample(1:n, size = n, replace = TRUE)\n  LSAT <- law$LSAT[i] # i is a vector of indices\n  GPA <- law$GPA[i]\n  R[b] <- cor(LSAT, GPA)\n}\n#output\n(se.R <- sd(R))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.128997\n```\n\n\n:::\n\n```{.r .cell-code}\nhist(R, prob = TRUE)\n```\n\n::: {.cell-output-display}\n![](06-resample_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nThe bootstrap estimate of se(R) is 0.129. The normal theory estimate for standard error of R is 0.115.\n:::\n\n::: {.callout-example title=\"Bootstrap Estimate of Standard Error using *boot* function\"}\nWe can also use the `boot(.)` function in the `boot` package to compute the bootstrap estimate of standard error.\n\nFirst, write a function that returns $\\hat \\theta(b)$, where the first argument to the function is the sample data, and the second argument is the vector $\\{i_1, \\dots , i_n\\}$ of indices. If the data is $x$ and the vector of indices is i, we need $x[i,1]$ to extract the first resampled variable, and x\\[i,2\\] to extract the second resampled variable. The code and output is shown below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_r <- function(x, i) {\n  # want correlation of columns 1 and 2\n  cor(x[i, 1], x[i, 2])\n}\n```\n:::\n\n\nThe printed summary of output from the boot function is obtained by the command boot or the result can be saved in an object for further analysis. Here we save the result in obj and print the summary.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(boot) #for boot function\nset.seed(777)\n(obj <- boot(data = bootstrap::law, statistic = my_r, R = 2000))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nORDINARY NONPARAMETRIC BOOTSTRAP\n\n\nCall:\nboot(data = bootstrap::law, statistic = my_r, R = 2000)\n\n\nBootstrap Statistics :\n     original      bias    std. error\nt1* 0.7763745 -0.01075929   0.1364617\n```\n\n\n:::\n:::\n\n\nThe observed value $\\hat \\theta$ of the correlation statistic is labeled t1\\*. The bootstrap estimate of standard error of the estimate is $se(\\hat \\theta) =$ 0.1365, based on 2000 replicates. Note that the standard deviation of the replicates can be computed directly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(obj$t)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1364617\n```\n\n\n:::\n:::\n\n:::\n\n### Bootstrap Estimation of Bias\n\nRecall that a bias of an estimator $\\hat \\theta$ is defined as $$\n\\mathbb b(\\hat \\theta) = \\mathbb E[\\hat \\theta] - \\theta.\n$$\n\nAn example of a biased estimator is the MLE of variance, $\\hat{\\sigma}^2 = \\sum (X_i-\\bar{X}_n)^2/n$ of $\\sigma^2 = \\sum (X_i-\\bar{X}_n)^2/(n-1)$, which has expected value $(1 − 1/n)\\sigma^2$. Here, the bias is $−\\sigma^2/n$.\n\nThe bootstrap estimation of bias uses the bootstrap replicates of $\\hat \\theta$ to estimate the sampling distribution of $\\hat \\theta$. For the finite population $x = (x_1,\\dots , x_n)$, the parameter is $\\hat \\theta(x)$ and there are $B$ i.i.d. estimators $\\hat \\theta^{(b)}$. The sample mean of the replicates $\\{\\htt(b)\\}$ is unbiased for its expected value $\\mathbb E[\\hat \\theta^\\ast]$, so the bootstrap estimate of bias is\\\n$$\\mathbb b(\\hat \\theta) = \\hat \\theta^\\ast − \\hat \\theta,$$ where $\\hat \\theta^\\ast  = \\sum_{b=1}^B \\hat \\theta^{(b)}$, and $\\hat \\theta= \\hat \\theta(x)$ is the estimate computed from the original observed sample. (In bootstrap $F_n$ is sampled in place of $F_X$ , so we replace $\\theta$ with $\\hat \\theta$ to estimate the bias.)\n\n::: {.callout-note title = \"Remark for estimating bias\"}\n\n-   $\\oplus$ Positive bias indicates that $\\hat \\theta$ on average tends to overestimate $\\theta$,\n\n-   $\\ominus$ Negative bias is on average underestimate $\\theta$\n\n:::\n\n::: {.callout-example title=\"Bootstrap Estimate of Bias\"}\nIn the law data example, compute the bootstrap estimate of bias in the sample correlation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# sample estimate for n=15\ntheta.hat <- cor(law$LSAT, law$GPA)\n# bootstrap estimate of bias\nB <- 2000 # larger for estimating bias\nn <- nrow(law)\ntheta.b <- numeric(B)\nfor (b in 1:B) {\n  i <- sample(1:n, size = n, replace = TRUE)\n  LSAT <- law$LSAT[i]\n  GPA <- law$GPA[i]\n  theta.b[b] <- cor(LSAT, GPA)\n}\n(bias <- mean(theta.b - theta.hat))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.001063244\n```\n\n\n:::\n:::\n\n\nThe estimate of bias is -0.0011. Note that this is close to the estimate of bias returned by the boot function we used before.\n:::\n\n::: {.callout-example title=\"One more example of Bootstrap estimation of bias\"}\nThe `patch` data from the *bootstrap* package contains measurements of a certain hormone in the bloodstream of 8 subjects after wearing a medical patch. The parameter of interest is\n\n$$\n\\theta\\coloneqq\\frac{\\mathbb E(\\text { new })-\\mathbb E(\\text { old })}{\\mathbb E(\\text { old })-\\mathbb E(\\text { placebo })}\n$$\n\nIf $|\\theta| \\ge 0.20$, this indicates bioequivalence of the old and new patches. The statistic is $\\bar{Y} /\\bar{Z}$. Compute a bootstrap estimate of bias in the bioequivalence ratio statistic.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(patch, package = \"bootstrap\")\nhead(patch)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  subject placebo oldpatch newpatch    z     y\n1       1    9243    17649    16449 8406 -1200\n2       2    9671    12013    14614 2342  2601\n3       3   11792    19979    17274 8187 -2705\n4       4   13357    21816    23798 8459  1982\n5       5    9055    13850    12560 4795 -1290\n6       6    6290     9806    10157 3516   351\n```\n\n\n:::\n\n```{.r .cell-code}\nn <- nrow(patch) #in bootstrap package\nB <- 2000\ntheta.b <- numeric(B)\ntheta.hat <- mean(patch$y) / mean(patch$z)\n\nfor (b in 1:B) {\n  i <- sample(1:n, size = n, replace = TRUE)\n  y <- patch$y[i]\n  z <- patch$z[i]\n  theta.b[b] <- mean(y) / mean(z)\n}\nbias <- mean(theta.b) - theta.hat\nse <- sd(theta.b)\nresult <- data.frame(\n  Estimate = theta.hat,\n  Bias = bias,\n  SE = se,\n  CV = bias / se\n)\n\nknitr::kable(result, digits = 3, caption = \"Bootstrap results for correlation estimate\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Bootstrap results for correlation estimate\n\n| Estimate|  Bias|    SE|    CV|\n|--------:|-----:|-----:|-----:|\n|   -0.071| 0.006| 0.101| 0.061|\n\n\n:::\n:::\n\n\nIf $|\\b|/se \\le 0.25$, it is not usually necessary to adjust for bias. The $\\b$ is small relative to standard error ( $\\b/se < 0.08$), so in this example it is not necessary to adjust for bias.\n:::\n\n## Jackknife\n\nThe jackknife is another resampling technique used to estimate the bias and variance of a statistic.\n\nJackknife is similar to **leave-one-out cross-validation** (LOOCV). Let $\\bx= (x_1,\\dots,x_n)$ be an observed random sample, and denote the $i$th jackknife sample by $\\bx_{-i} = (x_1,\\dots,x_{i-1},x_{i+1},\\dots,x_n)$, that is, a subset of $\\bx$.\n\nJackknife can be used to:\n\n* Estimating bias, \n* Estimating standard error\n* Detecting influential observations\n* Many others\n\n\nFor the parameter of interest $\\theta$, if the statistics is $T(\\bx)=: \\htt$ is computed on the full\n\n\n\nJackknife is a special kind of *Cross-validation* where we *leave-one-out* (LOO) the observation, and calculate the quantities on the remaining data. To fix the idea, let $x=(x_1,\\dots,x_n)$ be the observed data of samele size $n$. The $i$th jackknife sample is defined as $x_{(i)}=(x_1,\\dots,x_{i-1},x_{i+1},\\dots,x_n)$, that is, the sample with the $i$th observation removed. Let $\\htt=T_n(x)$ be the estimator of the parameter of interest $\\theta$. The $i$th jackknife replicate is defined as $\\hat \\theta_{(i)}=T(x_{(i)})$, that is, the estimate computed from the $i$th jackknife sample. The jackknife estimate of bias is defined as\n\n### Jackknife Estimate of Bias\n\nIf $\\htt$ is a smooth statistic, then $\\htt_{(\\cdot)} = t(F_{n−1}(x_{(i)}))$, and the jackknife estimate of bias is \n$$\n\\hat{\\b}_{jack} = (n − 1)(\\overline{\\htt_{(\\cdot)}} − \\htt), \n$$ where \n$\\overline{\\hat \\theta_{(\\cdot)}}=\\frac{1}{n} \\sum_{i=1}^n \\hat \\theta_{(i)}$ is the average of the estimate from LOO samples, and $\\hat \\theta=\\hat \\theta(x)$ is the estimate from the original observed sample.\n\n::: {.callout-note title=\"Question: Where is $n-1$ coming from?\"}\nFor instance, in the case of $\\theta$ is the population variance $\\theta=\\sigma^2$. Let $x_1,\\dots,x_n$ be random samples from $F_X$, the variance is \n$$\n\\E[(X - \\mu)^2] =: \\theta,\n$$\nand the plug-in estimator is \n$$\n\\htt = \\frac{1}{n} \\sum_{i=1}^n (x_i - \\bar x_n)^2.\n$$\nThis estimator $\\htt$ is biased, and the bias is \n$$\n\\b(\\htt)=\\E\\left[\\htt-\\theta\\right]=\\frac{n-1}{n} \\sigma^2-\\sigma^2=-\\frac{\\sigma^2}{n}.\n$$\nSince Jackknife is a resampling method, we compute the jackknife replicates $\\hat \\theta_{(i)}$ by leaving one observation out for each of the $i$ on sample size $n-1$, so the bias in the jackknife replicates is $-\\sigma^2/(n-1)$. Thus, for each $i,~i=1,\\dots,n$, we have\n$$\n\\begin{aligned}\n\\E\\left[\\htt_{(i)}-\\htt\\right] & =\\E\\left[\\htt_{(i)}-\\theta\\right]-\\E[\\htt-\\theta] \\\\\n& =\\b\\left(\\htt_{(i)}\\right)-\\b(\\htt) \\\\\n& =-\\frac{\\sigma^2}{n-1}-\\left(-\\frac{\\sigma^2}{n}\\right) =-\\frac{\\sigma^2}{n(n-1)}=\\frac{\\b(\\htt)}{n-1} .\n\\end{aligned}\n$$\nTherefore, the $n-1$ factor appears in the jackknife estimate of bias formula results the unbiased estimate of the bias. \n:::\n\n::: {.callout-note title=\"Leave one out (LOO) in R\"}\nIn R, we can use the `x[-i]` to perform LOO operation in a vector $x=(x_1,\\dots,x_n)$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(2, 4, 6, 8, 10)\nx[-3] # leave the 3rd element out\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  2  4  8 10\n```\n\n\n:::\n:::\n\n\n:::\n\n\n::: {.callout-example title=\"Jackknife Estimate of Bias\"}\nCompute the jackknife estimate of bias for the patch data in the `bootstrap` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(patch, package = \"bootstrap\")\nn <- nrow(patch)\ny <- patch$y\nz <- patch$z\ntheta.hat <- mean(y) / mean(z)\nprint (theta.hat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.0713061\n```\n\n\n:::\n\n```{.r .cell-code}\n#compute the jackknife replicates, LOO estimates\ntheta.jack <- numeric(n)\nfor (i in 1:n) {\n  theta.jack[i] <- mean(y[-i]) / mean(z[-i])\n}\n(bias <- (n - 1) * (mean(theta.jack) - theta.hat) )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.008002488\n```\n\n\n:::\n:::\n\n\n:::\n\n### Jackknife Estimate of Standard Error\n\nThe jackknife estimate of standard error (se) is given by\n$$\n\\boxed{\\widehat{s e}_{j a c k}=\\sqrt{\\frac{n-1}{n} \\sum_{i=1}^n\\left(\\hat{\\theta}_{(i)}-\\overline{\\hat{\\theta}_{(\\cdot)}}\\right)^2}},\n$$\nfor smooth statistics $\\htt$.\n\n::: {.callout-note title=\"Where is the $(n-1)/n$ coming from?\"}\nWe can first see an example in the context of the population mean. Suppose our parameter of interest is $\\theta=\\mu$ and $\\htt=\\bar{x}_n$ is its estimator. Then the variance estimator of the $\\htt$ is $\\sqrt{\\var(X)/n}$. Hence, the factor $(n-1)/n$ makes $\\widehat{s e}_{j a c k}$ an unbiased eestimator of the se of the mean.\n\n\nThe other way to look at this is that, we can consider a *plug-in estimate* of the se of the mean. For a continuous rv $X~F_X$, suppose we have the random samples from $F_X$ and obtain $\\bx=(x_1,\\dots,x_n)$. The plug-in estimate of\nthe variance of a them is the variance of $Y$ , where $Y$ is uniformly distributed on the sample $x_1,\\dots,x_n$. That is, \n\n$$\n\\begin{aligned}\n\\widehat{\\var}(Y) & =\\frac{1}{n} \\E[Y-\\E[Y]]^2=\\frac{1}{n} \\E[Y-\\bar{X}]^2 \\\\\n& =\\frac{1}{n} \\sum_{i=1}^n\\left(X_i-\\bar{X}\\right)^2 \\cdot \\frac{1}{n} \\\\\n& =\\frac{n-1}{n^2} S_X^2=\\frac{n-1}{n}[\\widehat{\\operatorname{se}}(\\bar{X})]^2 .\n\\end{aligned}\n$$\n\nThus, for the jackknife estimator of standard error, a factor of $\\{(n − 1)/n\\}/2$ gives the plug-in estimate of variance. The factors $\\{(n−1)/n\\}/2$ and $(n−1)/n$\nare approximately equal if $n$ is large. Researchers commented that the choice of the factor $(n − 1)/n$ instead of $\\{(n − 1)/n\\}/2$ is somewhat arbitrary.\n\n:::\n\n\n::: {.callout-example title=\"Jackknife Estimate of Standard Error\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(se <- sqrt((n-1) * mean((theta.jack - mean(theta.jack))^2)) |> round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1055\n```\n\n\n:::\n:::\n\n\n\nThe jackknife estimate of standard error is 0.1055 From the previous result for the bias, we have the estimated coefficient of variation\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncv <- bias/se\ntbl <- data.frame(\n  bias = bias,\n  se   = se,\n  cv   = cv\n)\n\n# Create kable table\nkable(tbl, digits = 3, caption = \"Bias, Standard Error, and Coefficient of Variation\") %>%\n  kable_styling(full_width = FALSE, position = \"center\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Bias, Standard Error, and Coefficient of Variation</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> bias </th>\n   <th style=\"text-align:right;\"> se </th>\n   <th style=\"text-align:right;\"> cv </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 0.008 </td>\n   <td style=\"text-align:right;\"> 0.106 </td>\n   <td style=\"text-align:right;\"> 0.076 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n:::\n\n### Jackknife does not always work\n\n::: {.callout-note title=\"Jackknife does not always work\"}\nQ: When does jackknife not work?\n\n\nJackknife does not work when the function $T(\\cdot)$ is **not a smooth** functional! Smoothness means that small changes in the data correspond to small changes in the statistic. For instance, median is a statisitics that is NOT smooth.\n:::\n\n::: {.callout-example title=\"Jackknife fails for Median\"}\nExample 8.8 (Failure of jackknife). In this example the jackknife estimate of standard error of the median is computed for a random sample of 10 integers from $1,\\dots, 100$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(777)\nn <- 10\nx <- sample(1:100, size = n)\n# jackknife estimate of se\nM <- numeric(n)\nfor (i in 1:n) { # leave one out\n  y <- x[-i]\n  M[i] <- median(y)\n}\nMbar <- mean(M)\n\n# bootstrap estimate of se\nMb <- replicate(1000, expr = {\n  y <- sample(x, size = n, replace = TRUE)\n  median(y)\n})\n\nest_jk <- sqrt((n - 1) / n * sum((M - Mbar)^2)) # jackknife estimate\nest_bs <- sd(Mb) # bootstrap estimate\n\n\ntbl <- data.frame(\n  Method = c(\"Jackknife\", \"Bootstrap\"),\n  Estimate = c(est_jk, est_bs)\n)\n\n# Display table\nkable(tbl, digits = 4, caption = \"Comparison of Jackknife and Bootstrap Estimates\") %>%\n  kable_styling(full_width = FALSE, position = \"center\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Comparison of Jackknife and Bootstrap Estimates</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Method </th>\n   <th style=\"text-align:right;\"> Estimate </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Jackknife </td>\n   <td style=\"text-align:right;\"> 52.5000 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Bootstrap </td>\n   <td style=\"text-align:right;\"> 19.2889 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nSomething fishy here?\n\nClearly something is wrong here, because the bootstrap estimate and the\njackknife estimate are far apart. The jackknife fails because the median is *not smooth*.\n:::\n\nIn this case, when the statistic is not smooth, the delete-d jackknife can be applied. If $\\sqrt{n}/{d}\\to 0$ and $n − d\\to\\infty$, then the delete-d jackknife\nis consistent for the median. The computing time increases because there are a large number of jackknife replicates when $n$ and $d$ are large.\n \n### Other variations of the Jackknife estimations\n\n* Jackknife ++\n* Weighted Jackknife\n* Block jackknife\n \n\n## Bootstrap Confidence Interval\n\nIn this section, we introduce a several approaches to obtaining approximate confidence intervals (CIs) for the target parameter in a bootstrap. The methods include \n\n1) standard normal bootstrap CI, \n2) basic bootstrap CI\n3) bootstrap percentile CI \n4) bootstrap t confidence interval\n\n### Standard Normal Bootstrap CI\n\nhe standard normal bootstrap confidence interval is the simplest approach, but not necessarily the best. Suppose that $\\htt$ is an estimator of parameter θ, and assume the standard error of the estimator is $se(\\htt)$. If $\\htt$ is a sample mean and the sample size is large, then the CLT implies that\n$$\n\\frac{\\hat{\\theta}-\\E[\\htt]}{s e(\\hat{\\theta})} \\approx N(0,1)=Z.\n$$\nHence, if $\\htt$ is unbiased of $\\theta$, then an approximate $100(1-\\alpha)$% CI for $\\theta$ is given by\n$$\n\\htt \\pm z_{1-\\alpha / 2} s e(\\htt),\n$$\nAdvantage: \n\n* easy to compute\n\nDisadvantage: requires several assumptions. \n\n1. $\\htt\\sim N$ or $\\htt$ is a sample mean and $n$ is large. \n2. $\\E[\\htt]=\\theta$.\n\n\nBias can be estimated and used to center the Z statistic, but the estimator is a rv, so the transformed variable is not normal.  Here we have treated $se(\\htt)$ as a *known parameter*, but in the bootstrap $se(\\htt)$ is estimated\n(the sample standard deviation of the replicates).\n\n### Basic Bootstrap CI\n\nThe basic bootstrap CI interval transforms the distribution of the replicates by **subtracting the observed statistic**. The quantiles of the transformed sample $\\htt^\\ast-\\htt$ are used to determine the confidence limits.\n\nThe $100(1 − \\alpha)$% confidence limits for the basic bootstrap confidence interval are\n$$\n\\boxed{\n(2\\htt - \\htt^\n\\ast_{1-\\alpha/2},\\quad 2\\htt - \\htt^\n\\ast_{\\alpha/2})}, \n$$\nwhee re $\\htt^\\ast_q$ is the $q$th quantile of the bootstrap replicates $\\htt^{(1)},\\dots ,\\htt^{(B)}$.\n\n::: {.callout-note title=\"Derivation of the Basic Bootstrap CI\"}\nLet $\\bx = (x_1,\\dots,x_n)$ be the observed sample, and a statistics $\\htt = T_n(\\bx)$ be the estimator of the parameter of interest $\\theta$ of the sampling distribution. Assume that we have $B$ replicates $\\htt^\\ast$ from bootstrap.\n\nTo obtain a **symmetric** $100(1-\\alpha)$% CI for $\\theta$, say $(L,U)$, we know that we need \n$$\nP(U \\le \\theta)= P(\\theta \\le L)=\\alpha/2.\n$$\n Then, we have \n $$\n\\alpha/2 = P(L \\ge \\theta) = P(L-\\htt \\ge \\theta - \\htt) = P(\\htt - \\theta \\le \\htt - L).\n $$\n \nNow, we have to solve it, we need $L-\\htt$ be the $1-\\alpha/2$'s quantile of the distribution of $\\htt - \\theta$. However, the distribution of $\\htt - \\theta$ is *unknown*. In bootstrap, we approximate the distribution of $\\htt - \\theta$ by the distribution of $\\htt^\\ast - \\htt$. Thus, we set $\\htt - L$ to be the $1-\\alpha/2$'s quantile of the distribution of $\\htt^\\ast - \\htt$, denoted as $\\htt^\\ast_{1-\\alpha/2}$, that is, $\\htt^\\ast_{1-\\alpha/2}-\\htt$. Then, we set $\\htt-L$ to be $\\htt^\\ast_{1-\\alpha/2}-\\htt$.\n \nSimilarly, for the upper limit $U$, we have \n $$\n\\alpha/2 = P(\\theta \\ge U) = P(\\theta - \\htt \\ge U - \\htt) = P(\\htt - \\theta \\le \\htt - U),\n $$\n which leads to $\\htt-U = \\htt_{\\alpha/2}^\\ast - \\htt$.\n We *move $\\htt$ to other side for both $L$ and $U$. As a result, we obtain\n$$\n(L,~U) = (2\\htt - \\htt^\\ast_{1-\\alpha/2},~2\\htt - \\htt^\\ast_{\\alpha/2}),\n$$\nwhich is the result of a basic bootstrap CI we state previously.\n:::\n\n\n### Bootstrap Percentile CI\n\nThis method use directly from the empirical distribution.\n\n\nA bootstrap percentile interval uses the empirical distribution of the bootstrap replicates as the reference distribution. The quantiles of the empirical\ndistribution are estimators of the quantiles of the sampling distribution of $\\htt$, so that these (random) quantiles may match the true distribution better when\nthe distribution of $\\htt$ is **not normal**. Suppose that $\\{\\htt^{(b)}\\}_{b=1}^B$ are the bootstrap replicates of the statistic $\\htt$. From the ecdf of the replicates, compute the $\\alpha/2$ quantile $\\htt_{\\alpha/2}$, and the $1 − \\alpha/2$ quantile $\\htt_{1-\\alpha/2}$.\n\nResearchers showed that this method some\ntheoretical advantages over the standard normal interval and somewhat better\ncoverage performance in practice.\n\n::: {.callout-note title=\"R command\"}\nThe `boot::boot.ci(.)` computes 5 types of bootstrap CI: \n\n1. basic\n2. normal\n3. percentile \n4. studentized\n5. BCa (bias-corrected and accelerated), which is an improved percentile intervals that aim to have better theoretical properties and better performance in practice.\n:::\n\n::: {.callout-example title=\"Bootstrap CIs on the patch ratio statistics\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(boot)\nset.seed(8670)\ndata(patch, package = \"bootstrap\")\n# function to compute the statistic\ntheta.boot <- function(dat, ind) {\n  \n  y <- dat[ind, 1]\n  z <- dat[ind, 2]\n  mean(y) / mean(z)\n}\n\n\n\n\ny <- patch$y\nz <- patch$z\ndat <- cbind(y, z)\nboot.obj <- boot(dat, statistic = theta.boot, R = 2000)\nprint(boot.obj)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nORDINARY NONPARAMETRIC BOOTSTRAP\n\n\nCall:\nboot(data = dat, statistic = theta.boot, R = 2000)\n\n\nBootstrap Statistics :\n      original     bias    std. error\nt1* -0.0713061 0.01265825   0.1047968\n```\n\n\n:::\n\n```{.r .cell-code}\n# \nprint(boot.ci(boot.obj,\n              type = c(\"basic\", \"norm\", \"perc\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS\nBased on 2000 bootstrap replicates\n\nCALL : \nboot.ci(boot.out = boot.obj, type = c(\"basic\", \"norm\", \"perc\"))\n\nIntervals : \nLevel      Normal              Basic              Percentile     \n95%   (-0.2894,  0.1214 )   (-0.3422,  0.0839 )   (-0.2265,  0.1995 )  \nCalculations and Intervals on Original Scale\n```\n\n\n:::\n:::\n\n\n  Recall that the old and new patches are bioequivalent if |θ| ≤ 0.20. Hence, the\ninterval estimates do not support bioequivalence of the old and new patches.\nNext we compute the bootstrap confidence intervals according to their defini-\ntions. Compare the following results with the boot.ci output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(knitr)\n\nalpha <- 0.05\n\n# normal\nCI_normal <- boot.obj$t0 + qnorm(c(alpha/2, 1 - alpha/2)) * sd(boot.obj$t)\n\n# basic\nCI_basic <- 2 * boot.obj$t0 - quantile(boot.obj$t, probs = c(1 - alpha/2, alpha/2), type = 1)\n\n# percentile\nCI_percentile <- quantile(boot.obj$t, probs = c(alpha/2, 1 - alpha/2), type = 6)\n\n# combine into data frame\nCI_table <- data.frame(\n  Method = c(\"Normal\", \"Basic\", \"Percentile\"),\n  Lower = c(CI_normal[1], CI_basic[1], CI_percentile[1]),\n  Upper = c(CI_normal[2], CI_basic[2], CI_percentile[2])\n)\n\n# display as kable\nkable(CI_table, digits = 4, caption = \"Bootstrap Confidence Intervals\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Bootstrap Confidence Intervals\n\n|      |Method     |   Lower|  Upper|\n|:-----|:----------|-------:|------:|\n|      |Normal     | -0.2713| 0.1287|\n|97.5% |Basic      | -0.3077| 0.0876|\n|2.5%  |Percentile | -0.2302| 0.1674|\n\n\n:::\n:::\n\n\n:::\n\n::: {.callout-note title = \"Remark\"}\nThe normal interval computed by boot.ci corrects for bias. Notice\nthat the boot.ci normal interval differs from our result by the bias\nestimate shown in the output from boot. This is confirmed by read-\ning the source code for the function. To view the source code for\nthis calculation, when the boot package is loaded, enter the command\ngetAnywhere(norm.ci) at the console. Also see norm.inter and [68]\nfor details of calculations of quantiles.\n:::\n\n::: {.callout-example title=\"Bootstrap CIs for correlation coefficients\"}\n\n\nExample 8.10 (Bootstrap confidence intervals for the correlation statis-\ntic). Compute 95% bootstrap confidence interval estimates for the correlation\nstatistic in the law data of Example 8.2.\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(boot)\ndata(law, package = \"bootstrap\")\nboot.obj <- boot(law,\n  R = 2000,\n  statistic = function(x, i) {\n    cor(x[i, 1], x[i, 2])\n  }\n)\nprint(boot.ci(boot.obj, \n              type = c(\"basic\", \"norm\", \"perc\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS\nBased on 2000 bootstrap replicates\n\nCALL : \nboot.ci(boot.out = boot.obj, type = c(\"basic\", \"norm\", \"perc\"))\n\nIntervals : \nLevel      Normal              Basic              Percentile     \n95%   ( 0.5151,  1.0364 )   ( 0.5901,  1.0946 )   ( 0.4582,  0.9627 )  \nCalculations and Intervals on Original Scale\n```\n\n\n:::\n:::\n\n\nAll three intervals cover the correlation $\\rho=0.76$ of the universe of all law schools in law82. One reason for the difference in the percentile and normal\nconfidence intervals could be that the sampling distribution of correlation statistic is not close to normal (see the histogram in Figure 8.1). When the sampling distribution of the statistic is approximately normal, the percentile interval will agree with the normal interval. \n:::\n\n### Bootstrap t CI\n\nEven if the distribution of $\\htt$ is normal and $\\E[\\htt]=\\theta$, the normal\ndistribution is not exactly correct for the Z statistic, because we estimate $se(\\htt)$. Nor can we claim that it is a Student t statistic, because the distribution\nof the bootstrap estimator $se(\\htt)$ is unknown. **The bootstrap t interval does not use a Student t distribution as the reference distribution**. Instead, the sampling distribution of a *t type* statistic (a studentized statistic) is generated by resampling. Let $\\bx = (x_1, \\dots, x_n)$ be an observed sample. The $100(1 − \\alpha)$% bootstrap t confidence interval is\n$$\n\\boxed{\n\\left(\\hat{\\theta}-t_{1-\\alpha / 2}^* \\widehat{s e}(\\hat{\\theta}), \\quad \\hat{\\theta}-t_{\\alpha / 2}^* \\widehat{s e}(\\hat{\\theta})\\right)},\n$$\n\nwhere $se(\\htt),~ t^\\ast_{\\alpha/2}$ and $t^\\ast_{1-\\alpha/2}$ are computed as outlined below.\n\n::: {.callout-algorithm title = \"Algorithm of Bootstrap t CI\"}\n\n1. Compute the observed statistic $\\htt$.\n2. For each replicate, indexed $b = 1, \\dots,B$:\n  (a) Sample with replacement from x to get the bth sample $\\bx^{(b)} = (x_1^{(b)}, \\dots , x_n^{(b)})$ \n  (b) Compute $\\htt^{(b)}$ from the $b$th sample $x^{(b)}$.\n  (c) Compute or estimate the standard error $\\widehat{se}(\\htt^{(b)})$ (a separate estimate for each bootstrap sample; a bootstrap estimate will resample\nfrom the current bootstrap sample $\\bx^{(b)}$, not $\\bx$).\n  (d) Compute the $b$th replicate of the *t* statistic,\n  $$t(b) = \\frac{\\htt^{(b)}−\\htt}{\\widehat{se}(\\htt^{(b)})}.$$ \n3. The sample of replicates $t^{(1)},\\dots t^{(B)}$ is the reference distribution for bootstrap $t$. Find the sample quantiles $t^\\ast_{\\alpha/2}$ and $t^\\ast_{1-\\alpha/2}$ from the ordered sample of replicates $t^{(b)}$.\n4. Compute $\\widehat{\\htt}$, the sample standard deviation of the replicates $\\htt^{(b)}$.\n5. Compute confidence limits\n$$\n\\left(\\hat{\\theta}-t_{1-\\alpha / 2}^* \\widehat{\\operatorname{se }}(\\hat{\\theta}), \\quad \\hat{\\theta}-t_{\\alpha / 2}^* \\widehat{\\operatorname{se}}(\\hat{\\theta})\\right) .\n$$\n\n:::\n\nOne disadvantage is the *computational time*!\n\nTo the bootstrap $t$ interval, typically $\\widehat{se}(\\htt^{(b)})$ must be obtained by bootstrap. This is *a bootstrap nested inside a bootstrap*. If $B = 1000$, for example, the bootstrap t confidence interval method takes approximately $1000$ times longer than any of the other methods.\n\n---\n\nHere, we see how to compute the bootstrap $t$ confidence interval for a univariate or a\nmultivariate sample $\\bx$. The required arguments to the function are \n\n* the sample data $\\bx$,  and\n* the function statistic that computes the statistic $T_n(\\bx)$. \n\nThe default values are:\n\n* significance level is $\\alpha=0.05$\n* number of bootstrap replicates $B=500$,\n* number of replicates for estimating standard error is $100$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboot.t.ci <-\n  function(x, B = 500, R = 100, level = .95, statistic) {\n    # compute the bootstrap t CI\n    x <- as.matrix(x)\n    n <- nrow(x)\n    stat <- numeric(B)\n    se <- numeric(B)\n\n    boot.se <- function(x, R, f) {\n      # local function to compute the bootstrap\n      # estimate of standard error for statistic f(x)\n      x <- as.matrix(x)\n      m <- nrow(x)\n      th <- replicate(R, expr = {\n        i <- sample(1:m, size = m, replace = TRUE)\n        f(x[i, ])\n      })\n      return(sd(th))\n    }\n    for (b in 1:B) {\n      j <- sample(1:n, size = n, replace = TRUE)\n      y <- x[j, ]\n      stat[b] <- statistic(y)\n      se[b] <- boot.se(y, R = R, f = statistic)\n    }\n    stat0 <- statistic(x)\n    t.stats <- (stat - stat0) / se\n    se0 <- sd(stat)\n    alpha <- 1 - level\n    Qt <- quantile(t.stats, c(alpha / 2, 1 - alpha / 2), type = 1)\n    names(Qt) <- rev(names(Qt))\n    CI <- rev(stat0 - Qt * se0)\n  }\n```\n:::\n\n\nWe then aim to apply this function to our problem in hand.\n\n\n::: {.callout-example title = \"Bootstrap t CI for patch ratio statistics\"}\n\nNow, we want to compute a 95% bootstrap $t$ confidence interval for the ratio statistic we discussed previously.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- cbind(patch$y, patch$z)\nstat <- function(dat) {\n  mean(dat[, 1]) / mean(dat[, 2])\n}\nci <- boot.t.ci(dat, statistic = stat, B = 2000, \n                R = 200)\nprint(ci)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      2.5%      97.5% \n-0.2733909  0.4381807 \n```\n\n\n:::\n:::\n\n\nThe upper confidence limit of the bootstrap $t$ confidence interval is much\nlarger than the three intervals in Example 9 and the bootstrap $t$ is the widest interval here. \n\n:::\n\n  \n## Others\n\nThere are other method to construct bootstrap CIs. Interested reader should read the reference book, Davison & Hinkley (1997).\n\n\n\n<!-- ---  -->\n<!-- The distribution of $X^\\ast$ is the empirical distribution $F_n$ of the sample $x$. The empirical distribution places mass $1/n$ at each observed data point. The bootstrap uses the empirical distribution as an estimate of the true but unknown distribution $F$. -->\n\n<!-- The bootstrap is a resampling method that allows estimation of the *sampling distribution* of almost any statistic using random sampling methods. -->\n\n<!-- -   Parametric bootstrap -->\n\n<!-- -   Nonparametric bootstrap: In nonparametric bootstrap, the distribution is not specified. -->\n\n<!-- ::: {.callout-example title=\"Simple example of Bootstrap\"} -->\n<!-- ```{r bootstrap-simple-example} -->\n<!-- set.seed(333) -->\n<!-- n <- 1E4 -->\n<!-- B <- 1E4 -->\n<!-- x <- rnorm(n, mean = 5, sd = 2) #original sample -->\n\n\n<!-- boot_means <- pbapply::pbsapply(1:B, function(i){ -->\n<!--   indices <- sample(1:n, size = n, replace = TRUE) #resample -->\n<!--   boot.sample <- x[indices] -->\n<!--   mean(boot.sample) -->\n<!-- }) -->\n<!-- mean(boot_means) -->\n<!-- hist(boot_means, breaks = 50, main = \"Bootstrap distribution of the mean\", xlab = \"Mean\") -->\n\n\n<!-- # Compute statistics -->\n<!-- true_mean <- 5 -->\n<!-- boot_mean <- mean(boot_means) -->\n<!-- df <- tibble(x = boot_means) -->\n<!-- # Plot -->\n<!-- ggplot(df, aes(x = x)) + -->\n<!--   geom_histogram(aes(y = ..density..), bins = 50, -->\n<!--                  fill = \"lightgreen\", color = \"black\", alpha = 0.7) + -->\n<!--   geom_density(color = \"darkgreen\", size = 1) + -->\n<!--   geom_vline(xintercept = true_mean, color = \"red\", linetype = \"dashed\", size = 1.1) + -->\n<!--   geom_vline(xintercept = boot_mean, color = \"blue\", linetype = \"solid\", size = 1.1) + -->\n<!--   labs( -->\n<!--     title = \"Bootstrap Distribution of the Sample Mean\", -->\n<!--     x = \"Bootstrap Mean\", -->\n<!--     y = \"Density\" -->\n<!--   ) + -->\n<!--   annotate(\"text\", x = true_mean, y = 0.3, label = \"True mean = 5\", color = \"red\", hjust = -0.1) + -->\n<!--   annotate(\"text\", x = boot_mean, y = 0.25, label = sprintf(\"Bootstrap mean = %.2f\", boot_mean), -->\n<!--            color = \"blue\", hjust = -0.1) + -->\n<!--   theme_minimal(base_size = 14) -->\n<!-- ``` -->\n<!-- ::: -->\n\n<!-- The bootstrap is a general tool for assessing statistical accuracy. First we describe the bootstrap in general, and then show how it can be used to estimate extra-sample prediction error. As with cross-validation, the boot- strap seeks to estimate the conditional error ErrT , but typically estimates well only the expected prediction error Err. -->\n\n<!-- The distribution of the finite population represented by the sample can be regarded as a pseudo-population with similar characteristics as the true population. By repeatedly generating random samples from this pseudo-population (resampling), the sampling distribution of a statistic can be estimated. Properties of an estimator such as *bias* or *standard error* can be estimated by resampling. -->\n\n<!-- Bootstrap estimates of a sampling distribution are analogous to the idea of density estimation. We construct a histogram of a sample to obtain an estimate of the shape of the density function. The histogram is not the density, but in a nonparametric problem, can be viewed as a reasonable estimate of the density. We have methods to generate random samples from completely specified densities; bootstrap generates random samples from the empirical distribution of the sample. -->\n\n<!-- The term *bootstrap* can refer to nonparametric bootstrap or parametric bootstrap. Monte Carlo methods that involve sampling from a fully specified probability distribution, such as methods of Chapter 7 are sometimes called parametric bootstrap. Nonparametric bootstrap is the subject of this chapter. In nonparametric bootstrap, the distribution is not specified. -->\n\n<!-- To generate a bootstrap random sample by resampling $x$, generate n random integers $\\{i_1,\\dots, i_n\\}$ uniformly distributed on $\\{1,\\dots , n\\}$ and select the bootstrap sample $x^∗ = (x_{i_1} ,\\dots, x_{i_n} )$. Suppose $\\theta$ is the parameter of interest ($\\theta$ could be a vector), and $\\hat \\theta$ is an estimator of $\\theta$. Then the bootstrap estimate of the distribution of $\\hat \\theta$ is obtained as follows. -->\n\n<!-- ## Applications -->\n\n<!-- These methods are widely used in statistical inference and have applications in various fields. -->\n\n## Side reading (Won't be on the exam)\n\n::: {.callout-note title=\"Normal theory for SE (will not be on exam)\"}\nNormal Approximation for Correlation SE\n\nFor a bivariate normal population, the sampling distribution of the sample correlation $r$ is approximately normal with variance\n\n$$\n\\operatorname{Var}(r) \\approx \\frac{(1 - \\rho^2)^2}{n - 1}.\n$$\n\nThus, the **standard error (SE)** under the normal approximation is\n\n$$\n\\operatorname{se}_{\\text{normal}}(r) = \\sqrt{\\frac{(1 - r^2)^2}{n - 1}}.\n$$\n\nIn the Law school example\n\nGiven: - $r = 0.7763745$ - $n = 15$\n\nWe can compute:\n\n$$\n1 - r^2 = 1 - (0.776)^2 = 1 - 0.602 = 0.398,\n$$ $$\n\\operatorname{Var}(r) \\approx \\frac{(0.398)^2}{14} = \\frac{0.158}{14} = 0.0113,\n$$ $$\n\\operatorname{se}(r) = \\sqrt{0.0113} = 0.106.\n$$\n\nThis gives a rough normal-theory estimate of **0.106**.\n\n-   For Fisher z-Transformation Approximation\n\nA more accurate approximation uses the **Fisher z-transform**:\n\n$$\nz = \\frac{1}{2}\\log\\!\\left(\\frac{1 + r}{1 - r}\\right),\n$$\n\nwhich is approximately normal with\n\n$$\n\\operatorname{Var}(z) = \\frac{1}{n - 3}.\n$$\n\nApplying the delta method:\n\n$$\n\\operatorname{se}(r) \\approx (1 - r^2)\\sqrt{\\frac{1}{n - 3}}.\n$$\n\nPlug in the values:\n\n$$\n\\operatorname{se}(r) = (1 - 0.776^2)\\sqrt{\\frac{1}{12}} = 0.398 \\times 0.289 = 0.115.\n$$\n\n✅ **Normal approximation (Fisher z) SE = 0.115**\n\nAlternatively, we may use the **Bootstrap Estimate** to compare with:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(bootstrap) # for the law data\nset.seed(123)\n\n# Sample data\nlaw <- data.frame(\n  LSAT = c(576, 635, 558, 578, 666, 580, 555, 661, 651, 605, 653, 575, 545, 572, 594),\n  GPA  = c(339, 330, 281, 303, 344, 307, 300, 343, 336, 313, 312, 274, 276, 288, 296)\n)\n\n# Sample correlation\nr <- cor(law$LSAT, law$GPA)\nn <- nrow(law)\n\n# Bootstrap estimate of SE\nB <- 200\nR <- replicate(B, {\n  i <- sample(1:n, size = n, replace = TRUE)\n  cor(law$LSAT[i], law$GPA[i])\n})\nse_boot <- sd(R)\n\n# Normal approximation\nse_normal <- sqrt((1 - r^2)^2 / (n - 1))\n\n# Fisher z-approximation\nse_fisher <- (1 - r^2) / sqrt(n - 3)\n\n# Display results\ndata.frame(\n  Method = c(\"Bootstrap\", \"Normal theory\", \"Fisher z-approximation\"),\n  SE = c(se_boot, se_normal, se_fisher)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  Method        SE\n1              Bootstrap 0.1200175\n2          Normal theory 0.1061676\n3 Fisher z-approximation 0.1146741\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Reference:\n\n- Davison, A.C. and Hinkley, D.V. (1997). [Bootstrap Methods and their Application](https://www.cambridge.org/core/books/bootstrap-methods-and-their-application/ED2FD043579F27952363566DC09CBD6A). Cambridge University Press.\n\n-   Section 7.11 in Hastie, T., Tibshirani R. and Friedman, J. (2008). [The Elements of Statistical Learning](https://www.sas.upenn.edu/~fdiebold/NoHesitations/BookAdvanced.pdf). Springer, 2nd edition.\n\n-   Chapter 8 of Rizzo, M.L. (2007). *Statistical Computing with R*. CRC Press, Roca Baton.\n\n-   Wu, C.F.J. (1986).[Bootstrap and Other Resampling Methods in Regression Analysis](https://projecteuclid.org/journals/annals-of-statistics/volume-14/issue-4/Jackknife-Bootstrap-and-Other-Resampling-Methods-in-Regression-Analysis/10.1214/aos/1176350142.full). *The Annals of Statistics*.\n\n------------------------------------------------------------------------\n\n## R Functions\n\nSome useful R functions for resampling methods:\n\n-   `sample()`: Generate random samples from a specified set of data points.\n\n-   `boot::boot()`: Perform bootstrap resampling and compute statistics.\n\n- `bootstrap`: A package that is associated with the book by Efron and Tibshirani (1993). It contains variety of the functions for bootstrap and jackknife, and the dataset used in the book. \n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}